version: "3.9"
networks:
  default:
    name: atw-net
services:
  db:
    container_name: db
    image: mongo:5
    ports:
      - 27017:27017
  api:
    depends_on:
      - db
    image: atw-api-image
    container_name: api
    build:
      context: .
      dockerfile: apps/ask-the-world-api/Dockerfile
    command: yarn start-local
    ports:
      - "9000:9000"
    # volumes:
    #   - ./apps/ask-the-world-api:/usr/src/app
    #   - /usr/src/app/node_modules
    #   - ./certs:/usr/src/certs
  app:
    depends_on:
      - api
    image: atw-fe-image
    container_name: fe
    build:
      context: .
      dockerfile: apps/ask-the-world-fe/Dockerfile
    command: yarn start-dev
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./apps/ask-the-world-fe:/usr/src/app
      - ./apps/ask-the-world-fe/node_modules:/usr/src/app/node_modules:cached
      - ./certs:/usr/src/certs
