version: "3.9"
networks:
  default:
    name: atw-net
services:
  db:
    container_name: atw-db
    image: mongo:5
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  stripe:
    container_name: atw-stripe
    image: stripe/stripe-cli:v1.10.3
    environment:
      - STRIPE_API_KEY=$STRIPE_API_KEY
    command: listen --forward-to atw-fe:3000/api/user/payment
  api:
    container_name: atw-api
    build:
      context: .
      dockerfile: config/Dockerfile.api
      args:
        - PAT=$PAT
    command: yarn start-local
    ports:
      - "9100:9100"
    environment:
      - NODE_ENV=$NODE_ENV
      - API_PORT=$API_PORT
      - API_PORT_TEST=$API_PORT_TEST
      - FE_URL=$FE_URL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
      - AUTH_SECRET=$AUTH_SECRET
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_PASS=$EMAIL_PASS
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_URI=$MONGO_URI
      - MONGO_URI_LOCAL=$MONGO_URI_LOCAL
      - MONGO_URI_TEST=$MONGO_URI_TEST
      - MONGO_URI_STAGING=$MONGO_URI_STAGING
      - MONGO_URI_PROD=$MONGO_URI_PROD
      - MONGO_URI_MASTER=$MONGO_URI_MASTER
      - HONEYBADGER_API_KEY=$HONEYBADGER_API_KEY
      - FULL_ACCOUNT_PAYMENT_REQUIRED=$FULL_ACCOUNT_PAYMENT_REQUIRED
  fe:
    container_name: atw-fe
    build:
      context: .
      dockerfile: config/Dockerfile.fe
      args:
        - PAT=$PAT
    command: yarn start-dev
    ports:
      - "3100:3100"
      - "8100:8100"
      - "10100:10100"
    environment:
      - NODE_ENV=$NODE_ENV
      - CLIENT_PORT=$CLIENT_PORT
      - SERVER_PORT=$SERVER_PORT
      - API_URL=$API_URL
      - API_PATH=$API_PATH
      - AWS_BUCKET_URL=$AWS_BUCKET_URL
      - DONATION_PAYMENT_LINK=$DONATION_PAYMENT_LINK
      - FULL_ACCOUNT_PAYMENT_LINK=$FULL_ACCOUNT_PAYMENT_LINK
      - RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY
    volumes:
      - ./coverage:/usr/src/ask-the-world-fe/coverage
  shared:
    container_name: atw-shared
    build:
      context: .
      dockerfile: config/Dockerfile.shared
      args:
        - PAT=$PAT
