version: "3.9"
networks:
  default:
    name: atw-net
services:
  db:
    container_name: db
    image: mongo:5
    ports:
      - 27017:27017
  api:
    depends_on:
      - db
    container_name: api
    build:
      context: .
      dockerfile: config/Dockerfile.api
      args:
        - PAT=$PAT
    command: yarn start-local
    ports:
      - "9000:9000"
  fe:
    depends_on:
      - api
    container_name: fe
    build:
      context: .
      dockerfile: config/Dockerfile.fe
      args:
        - PAT=$PAT
    command: yarn start-dev
    ports:
      - "3000:3000"
      - "8000:8000"
