FROM node:16

WORKDIR /usr/src
RUN git clone https://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@github.com/Karmello/ask-the-world-fe.git

WORKDIR /usr/src/ask-the-world-fe
RUN yarn install

WORKDIR /usr/src/ask-the-world-fe/env
RUN cp env.local env

COPY certs /usr/src/certs
