FROM node:16

ARG PAT
ENV PAT=${PAT}

WORKDIR /usr/src
RUN git clone https://$PAT@github.com/Karmello/ask-the-world-api.git

WORKDIR /usr/src/ask-the-world-api
RUN yarn install

WORKDIR /usr/src/ask-the-world-api/env
RUN cp .env.local .env

COPY certs /usr/src/certs
