FROM node:20.10

ARG PAT
ENV PAT=${PAT}

WORKDIR /usr/src
RUN git clone https://$PAT@github.com/Karmello/ask-the-world-shared.git

WORKDIR /usr/src/ask-the-world-shared
RUN yarn install

ENTRYPOINT ["tail", "-f", "/dev/null"]
