FROM node:22.13.1

ARG PAT
ENV PAT=${PAT}

WORKDIR /usr/src
RUN git clone https://$PAT@github.com/Karmello/cat-fe.git

WORKDIR /usr/src/cat-fe
RUN yarn clone-shared

WORKDIR /usr/src/cat-fe
RUN yarn install
