FROM node:22.13.1

ARG PAT
ENV PAT=${PAT}

WORKDIR /usr/src
RUN git clone https://$PAT@github.com/Karmello/cat-shared.git

WORKDIR /usr/src/cat-shared
RUN yarn install

ENTRYPOINT ["tail", "-f", "/dev/null"]
