FROM node:22.13

ARG PAT
ENV PAT=${PAT}

WORKDIR /opt
RUN wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian11-x86_64-100.7.5.deb && \
    apt install ./mongodb-database-tools-*.deb && \
    rm -f mongodb-database-tools-*.deb

WORKDIR /usr/src
RUN git clone https://$PAT@github.com/Karmello/cat-api.git

WORKDIR /usr/src/cat-api
RUN yarn clone-shared

WORKDIR /usr/src/cat-api
RUN yarn install
