FROM node:16

ARG PAT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV PAT=${PAT}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

WORKDIR /usr/src
RUN git clone https://$PAT@github.com/Karmello/ask-the-world-fe.git

WORKDIR /usr/src/ask-the-world-fe
RUN yarn install

COPY certs /usr/src/certs
